#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import Gradient kivy_gradient.Gradient
#:import GradientLabel kivy_gradient.Gradient
BoxLayout:
    orientation: 'vertical'
    canvas.before:
        Rectangle:
            pos:self.pos
            size:self.size
            texture: Gradient.vertical(get_color_from_hex('141414'),get_color_from_hex('070606'))
    Image:
        source: 'Icons/grid.png'
        fit_mode : 'cover'

        Image:
            source : 'Icons/cruffin_tech.png'
            center_x : self.parent.center_x
            top: self.parent.top
        Image:
            source: 'Icons/disconnected.png'
            center_x : self.parent.center_x
            top : self.parent.top - dp(75)
            size_hint: None, None
            size: dp(75), dp(75)
            LongpressButton:
                name: 'none'
                center_x : self.parent.center_x
                center_y: self.parent.center_y
                size: self.parent.size
                background_color: 0,0,0,0
                long_press_time : 10

                on_long_press : print('long')

        BoxLayout:
            orientation: 'vertical'
            center_x : self.parent.center_x
            center_y: self.parent.center_y
            size_hint: None, None
            size: root.width,root.height
           
            
            ScreenManager:
                id: screenmanager
                Screen:
                    name : 'connect'
                    Image:
                        source: 'Icons/ins.png'
                        center_x : self.parent.center_x
                        center_y : self.parent.center_y + dp(50)
                        size_hint: None, None
                        size: dp(400), dp(400)

                    Image: 
                        source: 'Icons/bottom.png'
                        center_x: self.parent.center_x
                        center_y : dp(-75)
                        size_hint: None, None
                        size : root.width,dp(400)

                    ImageButton:
                        on_press : 
                            self.source = 'Icons/connect_button_down.png'
                        on_release: 
                            app.on_button_connect()
                            self.source = 'Icons/connect_button_up.png'
                        
                        source : 'Icons/connect_button_up.png'
                        center_x : self.parent.center_x
                        center_y : dp(100)
                        size_hint: None, None
                        size: dp(175), dp(175)

                Screen:
                    name: 'connecting'
                    BoxLayout:
                        orientation: 'vertical'
                        Label:
                            text: 'connect'
                            font_name:'Lexend-Medium'
                            font_size:dp(20)

                Screen:
                    name:'main'
                    Image:
                        source:'Icons/enter_text.png'
                        center_x : self.parent.center_x
                        top : self.parent.top - dp(10)
                        size_hint: None, None
                        size: dp(400), dp(400)

                    MDTextField:
                        center_x: self.parent.center_x
                        top: self.parent.top - dp(250)
                        size_hint: None,None
                        size: self.parent.width * 0.9,dp(100)

                        hint_text: 'Enter Message'
                        mode : 'fill'
                        max_text_length: 25
                        line_color_normal: get_color_from_hex('3E4147')
                        fill_color_normal: get_color_from_hex('232325')
                        text_color_normal: get_color_from_hex('3E4147')
                        hint_text_color_normal: get_color_from_hex('3E4147')
                        fill_color_focus: get_color_from_hex('323234')
                    
                    ImageButton:

                        on_press: 
                            self.source = 'Icons/print_button_down.png'
                        on_release:
                            app.on_button_print()
                            self.source = 'Icons/print_button_up.png'

                        source: 'Icons/print_button_up.png'
                        center_x : self.parent.center_x
                        top : self.parent.top - dp(340)
                        size_hint: None, None
                        size: self.parent.width * 0.9,dp(100)

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint: None, None
                        size: self.parent.width,dp(75)
                        canvas.before:
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [dp(20),dp(20),dp(0),dp(0)]
                                texture: Gradient.vertical(get_color_from_hex("0A0B0A"),get_color_from_hex("141515"))
                        AnchorLayout:
                            anchor_x:'left'
                            anchor_y:'center'
                            size_hint_x: None
                            width: self.parent.width * 0.5
                            padding: dp(20)
                            Label:
                                text: 'Facing issues?'
                                font_name:'Lexend-Medium'
                                font_size:dp(15)
                                pos_hint: {'center_x': 0.1,'center_y': 0.5}

                        AnchorLayout:
                            anchor_x:'right'
                            anchor_y:'center'
                            size_hint_x: None
                            width: self.parent.width * 0.5
                            padding: dp(20)
                            ImageButton:
                                on_press: 
                                    self.source = 'Icons/reset_button_down.png'
                                on_release: 
                                    app.on_button_reset()
                                    self.source = 'Icons/reset_button_up.png'

                                source: 'Icons/reset_button_up.png'
                                size_hint_x: 0.5

